# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  system.debug: true

steps:
  - bash: ./build.sh
    enabled: false
   
  - script: echo hello > $(Build.ArtifactStagingDirectory)\test.txt
  - script: echo Version=$(Build.SourceVersion)
  
  - task: PublishBuildArtifacts@1
    enabled: false
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop
  
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github-kt
      repositoryName: 'koczkatamas/pipelines-test' 
      action: 'create'
      target: '$(Build.SourceVersion)'
      tagSource: manual
      tag: '1.0.0.1'
      releaseNotesSource: input
      releaseNotes: 'Release notes text'
