# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    rem curl --remote-name https://storage.googleapis.com/chrome-infra/depot_tools.zip
    rem unzip -d depot_tools -o depot_tools.zip
    rem cd depot_tools
    rem git checkout .
    rem cd ..
    set PATH=%PATH%;%CD%\depot_tools
  displayName: 'Download depot_tools'
- script: |
    echo %PATH%
    displayName: 'Show path'
- script: |
    export DEPOT_TOOLS_WIN_TOOLCHAIN=0
    gclient config --unmanaged https://pdfium.googlesource.com/pdfium.git
    gclient sync
  displayName: 'Download PDFium'
