# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    curl --remote-name https://storage.googleapis.com/chrome-infra/depot_tools.zip
    unzip -d depot_tools -o depot_tools.zip
    cd depot_tools
    git checkout .
    cd ..
    ECHO ##vso[task.prependpath]%CD%\depot_tools
  displayName: 'Download depot_tools'
- script: set
  displayName: 'Show environment variables'
- script: |
    set DEPOT_TOOLS_WIN_TOOLCHAIN=0
    gclient.bat config --unmanaged https://pdfium.googlesource.com/pdfium.git
    gclient.bat sync
  displayName: 'Initialize gclient'
- script: |
    echo before dir
    dir
    echo after dir
    cd pdfium
    echo "set:"
    set
    echo "where download_from_google_storage.bat"
    where download_from_google_storage.bat
    echo "download_from_google_storage.bat"
    download_from_google_storage.bat -b chromium-browser-clang/rc -d build/toolchain/win/rc/win
  displayName: 'Download PDFium'
- script: |
    dir
  displayName: 'Show pdfium contents'
